[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "napari-nucleome"
authors = [{name = "Yang Zhang", email = "yangz6@andrew.cmu.edu"}]
dynamic = ["version", "description"]
